# Ce ficher contient la configuration du plugin d'atouts de Luminaria.

prices:
  force: 100000
  speed: 800
  haste: 600
  nightvision: 500
  fireresistance: 700
# Prix en $ donc 100 = 100$ par example.
