# Main config for the Atouts plugin
# Handles player perks, permissions, and commands

name: Atouts
version: 1.0.0
main: fr.senaxzzonyt.atouts.Main
api-version: 1.13
description: Advanced perks management for Minecraft players
depend:
  - Vault
  - Essentials

commands:
  atouts:
    description: Main command for all perks actions
    usage: /atouts <give|delete|check|reload|help> <player> [perk]

permissions:
  atouts.use:
    default: true
    description: Allows use of perks
  atouts.reload:
    default: op
    description: Allows reloading the plugin
  atouts.give:
    default: op
    description: Lets you grant a perk to a player
  atouts.delete:
    default: op
    description: Lets you remove perks from a player
  atouts.checkpurchases:
    default: op
    description: Shows a player's purchased perks
  atouts.help:
    default: true
    description: Shows plugin command help
  atouts.force:
    default: false
    description: Grants Force perk (Strength I)

  atouts.speed:
    default: false
    description: Grants Speed perk (Speed I)

  atouts.haste:
    default: false
    description: Grants Haste perk (Haste I)

  atouts.nightvision:
    default: false
    description: Grants Night Vision perk (Night Vision I)

  atouts.fireresistance:
    default: false
    description: Grants Fire Resistance perk (Fire Resistance I)